version: '3.8'
services:
  cortex-service:
    build: ./cortex-service
    volumes:
      - ./cortex-service:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "9000:9000"
      - "9001:9001"
    command: npm run dev
    env_file:
      - .env

  # generation-service:
  #   build: ./generation-service
  #   volumes:
  #     - ./generation-service:/usr/src/app
  #   ports:  
  #     - "5001:5001"
  #   command: python -u watcher.py

  ui:
    build: ./ui
    volumes:
      - ./ui:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
